#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/ringd
  
  rm -rf build/* myApps/* 
  
  pySloc -L py ringClient ringDaemon  -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
