#!/usr/bin/python3
# ~/dev/py/ringd/ringClient

""" Collect options for the ringd client and invoke it. """

import os
# import re
import sys
import time
from argparse import ArgumentParser

from optionz import dump_options
#import upax
from xlattice import (HashTypes, check_hashtype,
                      parse_hashtype_etc, fix_hashtype)

from ringd import(__version__, __version_date__,
                  RINGD_APP_DIR, RINGD_APP_NAME, RING_HOST_INFO_FILE,
                  RINGD_PORT)

# from ringd.daemon import *


def invoke_the_client(options):
    """ XXX STUB """
    _ = options


def main():
    """ Collect options for the ringd client. """

    timestamp = "%04d%02d%02d-%02d%02d%02d" % time.gmtime()[:6]

    # -- program defaults -------------------------------------------

    # -- check for config file --------------------------------------

    # -- parse the command line -------------------------------------
    # see docs.python.org/library/argparse.html
    parser = ArgumentParser(
        'client inserting CLJ postings into the house ring')

    parser.add_argument('-a', '--app_dir', default=RINGD_APP_DIR,
                        help='where we keep client data')

    parser.add_argument('-H', '--host_info_file', default=RING_HOST_INFO_FILE,
                        help='base name of the file')

    parser.add_argument('-j', '--just_show', action='store_true',
                        help='show args and exit')

    parser.add_argument('-L', '--log_dir', default='logs',
                        help='name of log directory')

    parser.add_argument('-n', '--app_name', default=RINGD_APP_NAME,
                        help="name of the ring client's configuration subdirectory")

    parser.add_argument('-p', '--port', default=RINGD_PORT,
                        help='port the daemon listens on')

    parser.add_argument('-T', '--testing', action='store_true',
                        help='test run - write to ./testU')

    parser.add_argument('-t', '--show_timestamp', action='store_true',
                        help='show run timestamp')

    parser.add_argument('-u', '--u_dir', default='U',
                        help='base name of  U/ directory, defaults to U')

    parser.add_argument('-V', '--show_version', action='store_true',
                        help='show version number and date')

    parser.add_argument('-z', '--no_changes', action='store_true',
                        help="don't actually write anything to disk")

    parse_hashtype_etc(parser)

    args = parser.parse_args()      # a Namespace object

    # -- fixups -----------------------------------------------------
    fix_hashtype(args)

    args.pgm_name_and_version = "%s client v%s %s" % (
        args.app_name, __version__, __version_date__)

    # the order of these statements is significant --------
    if args.testing:
        args.app_dir = 'myApps'
    args.config_dir = os.path.join(args.app_dir, args.app_name)
    args.path_to_host_info = os.path.join(args.config_dir, args.host_info_file)
    args.log_dir = os.path.join(args.config_dir, args.log_dir)
    # end ordered statements ------------------------------

    args.timestamp = timestamp

    # -- sanity checks ----------------------------------------------
    check_hashtype(args.hashtype)

    if not os.path.exists(args.app_dir):
        print("app directory '%s' does not exist" % args.app_dir)
        sys.exit(1)

    if not os.path.exists(args.config_dir):
        print("config directory '%s' does not exist" % args.config_dir)
        sys.exit(1)

    if not os.path.exists(args.log_dir):
        os.mkdir(args.log_dir)

    u_path_parts = args.u_dir.split('/')
    if len(u_path_parts) > 1:
        print("u_dir may not contain any slashes: aborting")
        sys.exit(1)

    # fixups --------------------------------------------------------
    if args.u_dir and args.u_dir[-1] == '/':
        args.u_dir = args.u_dir[:-1]          # drop any trailing slash
    args.u_dir = os.path.join(args.config_dir, args.u_dir)

    if args.just_show or args.verbose:
        print(dump_options(args))

    # -- do it ------------------------------------------------------
    if not args.just_show:
        args.isClient = True
        invoke_the_client(args)

if __name__ == '__main__':
    main()
