[meta]
version = "0.1.0"

[project]
name = "ringd"
package = "ringd"
main_lang = "py"
version = "0.3.14"
version_date = "2018-01-01"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2012-2017"
description = "ring of servers connecting as dense mesh using fieldz for communications"
dev_status = "pre_alpha"
license = "mit"
state = "shared"
url = "https://jddixon.github.io/ringd"

[py]
packages = [ "ringd",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = [ "src/ring_client", "src/ring_daemon",]
ext_modules = []
distshare = [ "fieldz", "optionz", "rnglib", "upax_py", "wireops", "xlattice_py",]
env_vars = []
requirements = [ "ring_host_info_proto", "ring_proto_spec", "scandir", "setuptools",]
test_requirements = []
